### PR TITLE
Missing hashCode methods

### PR DESCRIPTION
**Pull request by amrox**
I used IntelliJ's helper to generate these. I hand-verified that the same fields are compared in `equals` and `hashcode`.

### CODE REVIEW

**Comment by amrox** [comment]
Code style updated. I didn't even notice since they were auto-gerenated. Thanks.

Do you want me to convert them to the new Java 8 / guava style?

I don't have a strong preference. I was just trying to hit compiler warnings zero.

**Comment by raygreenwell** [comment]
They're fine the way they are.

**Comment by amrox** [comment]
If everything looks OK, can you merge it?

**Comment by mjohnson-ooo** [comment]
We can't merge it yet.  For now, keep the new work on this fork.  I'd even go so far as to change the major version to 2, and we can setup a build for the java 8 version of library.  We've got some Java 6 dependencies that need to be cleaned up first and the master properly tied off with that before we bring this all in.

**Comment by amrox** [comment]
Ok. But to be clear, this is just adding missing hashcode methods, not adding Java 8 support. I could be wrong, but I don't think this will break Java 6.

**Comment by raygreenwell** [comment]
What's the point of this?:

(_alphaTestRef != +0.0f ? Float.floatToIntBits(_alphaTestRef) : 0);

It seems like an optimization. I'm sure 0.0f has an intBits representation as well...

**Pull request merged**
